services:
  war:
    build:
      args:
        ENVIRONMENT: dev
        PORT: 5000
        USER: war
        GROUP: darksiders
      context: .
      dockerfile: Dockerfile
    container_name: war
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - warnet
      - busnet
      - cachenet
      - dbnet
    secrets:
      - source: db_ca_crt
        target: ca.crt
      - source: db_client_root_key
        target: client.root.key
      - source: db_client_root_crt
        target: client.root.crt

  war-test:
    image: python:3.13.3-alpine
    container_name: war-test
    restart: "no"
    env_file:
      - .env
    networks:
      - warnet
      - busnet
      - cachenet
      - dbnet
    working_dir: /app
    volumes:
      - .:/app
    secrets:
      - source: db_ca_crt
        target: ca.crt
      - source: db_client_root_key
        target: client.root.key
        mode: 0600
      - source: db_client_root_crt
        target: client.root.crt
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements/dev.txt &&
        pytest tests
      "

networks:
  warnet:
    driver: bridge